/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_proxyAllocationRequest_2eproto__INCLUDED
#define PROTOBUF_C_proxyAllocationRequest_2eproto__INCLUDED

//THIS NEEDS TO CHANGE
#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _ProxyAllocationRequest ProxyAllocationRequest;
typedef struct _ProxyAllocationResponse ProxyAllocationResponse;


/* --- enums --- */


/* --- messages --- */

struct  _ProxyAllocationRequest
{
  ProtobufCMessage base;
  char *username;
  char *password;
  size_t n_params;
  char **params;
};
#define PROXY_ALLOCATION_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proxy_allocation_request__descriptor) \
    , NULL, NULL, 0,NULL }


struct  _ProxyAllocationResponse
{
  ProtobufCMessage base;
  size_t n_capabilities;
  char **capabilities;
};
#define PROXY_ALLOCATION_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proxy_allocation_response__descriptor) \
    , 0,NULL }


/* ProxyAllocationRequest methods */
void   proxy_allocation_request__init
                     (ProxyAllocationRequest         *message);
size_t proxy_allocation_request__get_packed_size
                     (const ProxyAllocationRequest   *message);
size_t proxy_allocation_request__pack
                     (const ProxyAllocationRequest   *message,
                      uint8_t             *out);
size_t proxy_allocation_request__pack_to_buffer
                     (const ProxyAllocationRequest   *message,
                      ProtobufCBuffer     *buffer);
ProxyAllocationRequest *
       proxy_allocation_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proxy_allocation_request__free_unpacked
                     (ProxyAllocationRequest *message,
                      ProtobufCAllocator *allocator);
/* ProxyAllocationResponse methods */
void   proxy_allocation_response__init
                     (ProxyAllocationResponse         *message);
size_t proxy_allocation_response__get_packed_size
                     (const ProxyAllocationResponse   *message);
size_t proxy_allocation_response__pack
                     (const ProxyAllocationResponse   *message,
                      uint8_t             *out);
size_t proxy_allocation_response__pack_to_buffer
                     (const ProxyAllocationResponse   *message,
                      ProtobufCBuffer     *buffer);
ProxyAllocationResponse *
       proxy_allocation_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proxy_allocation_response__free_unpacked
                     (ProxyAllocationResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ProxyAllocationRequest_Closure)
                 (const ProxyAllocationRequest *message,
                  void *closure_data);
typedef void (*ProxyAllocationResponse_Closure)
                 (const ProxyAllocationResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proxy_allocation_request__descriptor;
extern const ProtobufCMessageDescriptor proxy_allocation_response__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_proxyAllocationRequest_2eproto__INCLUDED */
