/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "proxyAllocationRequest.pb-c.h"
void   proxy_allocation_request__init
                     (ProxyAllocationRequest         *message)
{
  static ProxyAllocationRequest init_value = PROXY_ALLOCATION_REQUEST__INIT;
  *message = init_value;
}
size_t proxy_allocation_request__get_packed_size
                     (const ProxyAllocationRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proxy_allocation_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proxy_allocation_request__pack
                     (const ProxyAllocationRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proxy_allocation_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proxy_allocation_request__pack_to_buffer
                     (const ProxyAllocationRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proxy_allocation_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProxyAllocationRequest *
       proxy_allocation_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProxyAllocationRequest *)
     protobuf_c_message_unpack (&proxy_allocation_request__descriptor,
                                allocator, len, data);
}
void   proxy_allocation_request__free_unpacked
                     (ProxyAllocationRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proxy_allocation_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proxy_allocation_response__init
                     (ProxyAllocationResponse         *message)
{
  static ProxyAllocationResponse init_value = PROXY_ALLOCATION_RESPONSE__INIT;
  *message = init_value;
}
size_t proxy_allocation_response__get_packed_size
                     (const ProxyAllocationResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proxy_allocation_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proxy_allocation_response__pack
                     (const ProxyAllocationResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proxy_allocation_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proxy_allocation_response__pack_to_buffer
                     (const ProxyAllocationResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proxy_allocation_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProxyAllocationResponse *
       proxy_allocation_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProxyAllocationResponse *)
     protobuf_c_message_unpack (&proxy_allocation_response__descriptor,
                                allocator, len, data);
}
void   proxy_allocation_response__free_unpacked
                     (ProxyAllocationResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proxy_allocation_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proxy_allocation_request__field_descriptors[3] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ProxyAllocationRequest, username),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "password",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ProxyAllocationRequest, password),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "params",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(ProxyAllocationRequest, n_params),
    PROTOBUF_C_OFFSETOF(ProxyAllocationRequest, params),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned proxy_allocation_request__field_indices_by_name[] = {
  2,   /* field[2] = params */
  1,   /* field[1] = password */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange proxy_allocation_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proxy_allocation_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "proxyAllocationRequest",
  "ProxyAllocationRequest",
  "ProxyAllocationRequest",
  "",
  sizeof(ProxyAllocationRequest),
  3,
  proxy_allocation_request__field_descriptors,
  proxy_allocation_request__field_indices_by_name,
  1,  proxy_allocation_request__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor proxy_allocation_response__field_descriptors[1] =
{
  {
    "capabilities",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(ProxyAllocationResponse, n_capabilities),
    PROTOBUF_C_OFFSETOF(ProxyAllocationResponse, capabilities),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned proxy_allocation_response__field_indices_by_name[] = {
  0,   /* field[0] = capabilities */
};
static const ProtobufCIntRange proxy_allocation_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proxy_allocation_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "proxyAllocationResponse",
  "ProxyAllocationResponse",
  "ProxyAllocationResponse",
  "",
  sizeof(ProxyAllocationResponse),
  1,
  proxy_allocation_response__field_descriptors,
  proxy_allocation_response__field_indices_by_name,
  1,  proxy_allocation_response__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
